# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

r:
  - 3.2.3
  - release
  - devel

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R

addons:
  - apt
    - packages:
      - xvfb
      - libgdal-dev
      - libproj-dev
      - libcurl4-openssl-dev
      - libgtk-3-dev
      - libcairo2-dev
      - r-cran-rgtk2
      - r-cran-cairodevice
      - r-cran-rodbc

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
